from __future__ import annotations

from backend.app.core.domain_schema import EntitySpec, FieldSpec, RelationshipSpec


def build_entity_specs(*, namespace_prefix: str) -> tuple[EntitySpec, ...]:
    return (
        EntitySpec(
            class_name="CustomerProfile",
            redis_key_template=f"{namespace_prefix}_customer_profile:{{customer_id}}",
            file_name="customer_profiles.jsonl",
            id_field="customer_id",
            fields=(
                FieldSpec("customer_id", "str", "Public-safe demo customer identifier", is_key_component=True),
                FieldSpec("profile_reference", "str", "Profile reference", index="tag", no_stem=True),
                FieldSpec("display_name", "str", "Customer display name", index="text", weight=2.0),
                FieldSpec("salutation", "str", "Customer salutation", index="tag"),
                FieldSpec("customer_segment", "str", "Customer support segment such as Plus or Standard", index="tag"),
                FieldSpec("support_plan", "str", "Customer support plan label", index="tag"),
                FieldSpec("preferred_language", "str", "Preferred service language", index="tag"),
                FieldSpec("email", "str", "Read-only email on file", index="text", weight=1.3, no_stem=True),
                FieldSpec("mobile_number_masked", "str", "Masked mobile number on file", index="tag", no_stem=True),
                FieldSpec("postal_region_prefix", "str", "Partial postal region used for verification", index="tag"),
                FieldSpec("service_permissions", "dict[str, bool]", "Available self-service permissions for the customer"),
                FieldSpec("cache_group_id", "str", "Semantic cache cohort identifier", index="tag", no_stem=True),
            ),
            relationships=(
                RelationshipSpec(
                    "deposit_accounts",
                    "Deposit accounts belonging to this customer",
                    "customer_id",
                    "list[DepositAccount]",
                ),
                RelationshipSpec(
                    "support_cases",
                    "Support cases opened for this customer",
                    "customer_id",
                    "list[SupportCase]",
                ),
            ),
        ),
        EntitySpec(
            class_name="DepositAccount",
            redis_key_template=f"{namespace_prefix}_deposit_account:{{account_id}}",
            file_name="deposit_accounts.jsonl",
            id_field="account_id",
            fields=(
                FieldSpec("account_id", "str", "Unique deposit-account identifier", is_key_component=True),
                FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
                FieldSpec("account_nickname", "str", "Customer-facing account nickname", index="text", weight=1.6),
                FieldSpec("routing_code_masked", "str", "Masked routing identifier", index="tag", no_stem=True),
                FieldSpec("account_number_masked", "str", "Masked account number", index="tag", no_stem=True),
                FieldSpec("currency", "str", "Account currency", index="tag"),
                FieldSpec("account_status", "str", "Current account status", index="tag"),
                FieldSpec("ledger_balance", "float", "Current ledger balance"),
                FieldSpec("available_balance", "float", "Available balance"),
                FieldSpec("overdraft_available", "float", "Available overdraft amount"),
                FieldSpec("opened_at", "str", "Account opening timestamp"),
            ),
            relationships=(
                RelationshipSpec("customer", "Customer owning this account", "customer_id", "CustomerProfile"),
                RelationshipSpec("debit_cards", "Debit cards attached to this account", "account_id", "list[DebitCard]"),
                RelationshipSpec(
                    "support_interventions",
                    "Support interventions tied to this account",
                    "account_id",
                    "list[CardSupportIntervention]",
                ),
                RelationshipSpec(
                    "support_cases",
                    "Support cases tied to this account",
                    "account_id",
                    "list[SupportCase]",
                ),
            ),
        ),
        EntitySpec(
            class_name="DebitCard",
            redis_key_template=f"{namespace_prefix}_debit_card:{{card_id}}",
            file_name="debit_cards.jsonl",
            id_field="card_id",
            fields=(
                FieldSpec("card_id", "str", "Unique debit-card identifier", is_key_component=True),
                FieldSpec("account_id", "str", "Parent account identifier", index="tag"),
                FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
                FieldSpec("card_reference", "str", "Public-safe internal card reference", index="tag", no_stem=True),
                FieldSpec("product_name", "str", "Card product name", index="text", weight=1.4),
                FieldSpec("card_last4", "str", "Last four digits of the card", index="tag", no_stem=True),
                FieldSpec("card_status", "str", "Customer-visible card status", index="tag"),
                FieldSpec("status_summary", "str", "Plain-language explanation of the current card state", index="text"),
                FieldSpec("digital_wallet_status", "str", "Digital wallet provisioning status", index="tag"),
                FieldSpec("contactless_enabled", "bool", "Whether contactless use is enabled"),
                FieldSpec("cash_withdrawal_enabled", "bool", "Whether cash withdrawals are enabled"),
                FieldSpec("issued_at", "str", "Card issue timestamp"),
            ),
            relationships=(
                RelationshipSpec("account", "Account owning this card", "account_id", "DepositAccount"),
                RelationshipSpec("authorisations", "Card authorisations raised against this card", "card_id", "list[CardAuthorisation]"),
                RelationshipSpec(
                    "support_interventions",
                    "Support interventions tied to this card",
                    "card_id",
                    "list[CardSupportIntervention]",
                ),
            ),
        ),
        EntitySpec(
            class_name="CardAuthorisation",
            redis_key_template=f"{namespace_prefix}_card_authorisation:{{authorisation_id}}",
            file_name="card_authorisations.jsonl",
            id_field="authorisation_id",
            fields=(
                FieldSpec("authorisation_id", "str", "Unique card authorisation identifier", is_key_component=True),
                FieldSpec("card_id", "str", "Card identifier", index="tag"),
                FieldSpec("account_id", "str", "Account identifier", index="tag"),
                FieldSpec("risk_event_id", "str", "Linked risk event identifier", index="tag"),
                FieldSpec("merchant_name", "str", "Merchant name", index="text", weight=1.8),
                FieldSpec("merchant_category", "str", "Merchant category", index="tag"),
                FieldSpec("merchant_city", "str", "Merchant city", index="text"),
                FieldSpec("merchant_country", "str", "Merchant country code", index="tag"),
                FieldSpec("currency", "str", "Authorisation currency", index="tag"),
                FieldSpec("amount", "float", "Authorisation amount"),
                FieldSpec("channel", "str", "Card-present, contactless, wallet, or ecommerce", index="tag"),
                FieldSpec("authorisation_status", "str", "Approved or declined state", index="tag"),
                FieldSpec("decline_reason_customer", "str", "Customer-facing decline explanation", index="text"),
                FieldSpec("occurred_at", "str", "Authorisation timestamp"),
            ),
            relationships=(
                RelationshipSpec("card", "Card used for this authorisation", "card_id", "DebitCard"),
                RelationshipSpec("account", "Account used for this authorisation", "account_id", "DepositAccount"),
                RelationshipSpec("risk_event", "Risk event linked to this authorisation", "risk_event_id", "CardRiskEvent"),
            ),
        ),
        EntitySpec(
            class_name="CardRiskEvent",
            redis_key_template=f"{namespace_prefix}_card_risk_event:{{risk_event_id}}",
            file_name="card_risk_events.jsonl",
            id_field="risk_event_id",
            fields=(
                FieldSpec("risk_event_id", "str", "Unique card risk event identifier", is_key_component=True),
                FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
                FieldSpec("account_id", "str", "Account identifier", index="tag"),
                FieldSpec("card_id", "str", "Card identifier", index="tag"),
                FieldSpec("linked_authorisation_id", "str", "Linked authorisation identifier", index="tag"),
                FieldSpec("event_type", "str", "Risk event type", index="tag"),
                FieldSpec("event_status", "str", "Risk review status", index="tag"),
                FieldSpec("risk_reason_code", "str", "Operational risk reason code", index="tag"),
                FieldSpec("risk_summary", "str", "Plain-language summary of why the event was raised", index="text"),
                FieldSpec("detected_at", "str", "Detection timestamp"),
                FieldSpec("detection_source", "str", "Channel or service that raised the event", index="tag"),
                FieldSpec("card_action_taken", "str", "Action already applied to the card", index="tag"),
                FieldSpec("review_window", "str", "Expected review or verification window", index="text"),
            ),
            relationships=(
                RelationshipSpec("account", "Account tied to this risk event", "account_id", "DepositAccount"),
                RelationshipSpec("card", "Card tied to this risk event", "card_id", "DebitCard"),
                RelationshipSpec(
                    "linked_authorisation",
                    "Authorisation that triggered this risk event",
                    "linked_authorisation_id",
                    "CardAuthorisation",
                ),
                RelationshipSpec(
                    "support_interventions",
                    "Support interventions currently tied to this risk event",
                    "risk_event_id",
                    "list[CardSupportIntervention]",
                ),
            ),
        ),
        EntitySpec(
            class_name="CardSupportIntervention",
            redis_key_template=f"{namespace_prefix}_card_support_intervention:{{intervention_id}}",
            file_name="card_support_interventions.jsonl",
            id_field="intervention_id",
            fields=(
                FieldSpec("intervention_id", "str", "Unique support intervention identifier", is_key_component=True),
                FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
                FieldSpec("account_id", "str", "Account identifier", index="tag"),
                FieldSpec("card_id", "str", "Card identifier", index="tag"),
                FieldSpec("risk_event_id", "str", "Risk event identifier", index="tag"),
                FieldSpec("intervention_type", "str", "Type of intervention applied", index="tag"),
                FieldSpec("intervention_status", "str", "Current intervention status", index="tag"),
                FieldSpec("applied_at", "str", "When the intervention was applied"),
                FieldSpec("expires_at", "str | None", "When the temporary intervention expires if known"),
                FieldSpec("service_channel", "str", "Channel the customer can use next", index="tag"),
                FieldSpec("customer_message", "str", "Customer-facing explanation of the current safeguard", index="text"),
                FieldSpec("next_step_summary", "str", "Customer-facing summary of what can happen next", index="text"),
            ),
            relationships=(
                RelationshipSpec("account", "Account tied to this intervention", "account_id", "DepositAccount"),
                RelationshipSpec("card", "Card tied to this intervention", "card_id", "DebitCard"),
                RelationshipSpec("risk_event", "Risk event behind this intervention", "risk_event_id", "CardRiskEvent"),
                RelationshipSpec(
                    "recovery_options",
                    "Recovery options available for this intervention",
                    "intervention_id",
                    "list[CardRecoveryOption]",
                ),
            ),
        ),
        EntitySpec(
            class_name="CardRecoveryOption",
            redis_key_template=f"{namespace_prefix}_card_recovery_option:{{option_id}}",
            file_name="card_recovery_options.jsonl",
            id_field="option_id",
            fields=(
                FieldSpec("option_id", "str", "Unique recovery option identifier", is_key_component=True),
                FieldSpec("account_id", "str", "Account identifier", index="tag"),
                FieldSpec("card_id", "str", "Card identifier", index="tag"),
                FieldSpec("risk_event_id", "str", "Risk event identifier", index="tag"),
                FieldSpec("intervention_id", "str", "Intervention identifier", index="tag"),
                FieldSpec("option_code", "str", "Stable recovery option code", index="tag", no_stem=True),
                FieldSpec("option_label", "str", "Short customer-facing option label", index="text", weight=1.7),
                FieldSpec("option_type", "str", "currently_applied or alternative", index="tag"),
                FieldSpec("eligibility_status", "str", "Eligibility state for this option", index="tag"),
                FieldSpec("service_channel", "str", "Preferred service channel for this option", index="tag"),
                FieldSpec("expected_outcome", "str", "What the option does for the card or account", index="text"),
                FieldSpec("customer_note", "str", "Short plain-language note about the option", index="text"),
            ),
            relationships=(
                RelationshipSpec("account", "Account tied to this recovery option", "account_id", "DepositAccount"),
                RelationshipSpec("card", "Card tied to this recovery option", "card_id", "DebitCard"),
                RelationshipSpec("intervention", "Intervention this recovery option belongs to", "intervention_id", "CardSupportIntervention"),
                RelationshipSpec("risk_event", "Risk event tied to this option", "risk_event_id", "CardRiskEvent"),
            ),
        ),
        EntitySpec(
            class_name="SupportCase",
            redis_key_template=f"{namespace_prefix}_support_case:{{support_case_id}}",
            file_name="support_cases.jsonl",
            id_field="support_case_id",
            fields=(
                FieldSpec("support_case_id", "str", "Unique support case identifier", is_key_component=True),
                FieldSpec("customer_id", "str", "Customer identifier", index="tag"),
                FieldSpec("account_id", "str", "Account identifier", index="tag"),
                FieldSpec("card_id", "str", "Card identifier", index="tag"),
                FieldSpec("case_type", "str", "Support case type", index="tag"),
                FieldSpec("status", "str", "Current support case status", index="tag"),
                FieldSpec("opened_at", "str", "Case creation timestamp"),
                FieldSpec("channel", "str", "Channel used to open the case", index="tag"),
                FieldSpec("summary", "str", "Short support summary", index="text"),
                FieldSpec("latest_note", "str", "Most recent customer-facing note", index="text"),
            ),
            relationships=(
                RelationshipSpec("customer", "Customer tied to this support case", "customer_id", "CustomerProfile"),
                RelationshipSpec("account", "Account tied to this support case", "account_id", "DepositAccount"),
                RelationshipSpec("card", "Card tied to this support case", "card_id", "DebitCard"),
            ),
        ),
        EntitySpec(
            class_name="ServiceStatus",
            redis_key_template=f"{namespace_prefix}_service_status:{{service_status_id}}",
            file_name="service_statuses.jsonl",
            id_field="service_status_id",
            fields=(
                FieldSpec("service_status_id", "str", "Unique service-status identifier", is_key_component=True),
                FieldSpec("service_name", "str", "Stable shared service name", index="tag", no_stem=True),
                FieldSpec("incident_category", "str", "Type of service issue", index="tag"),
                FieldSpec("customer_scope", "str", "Who is affected by the issue", index="tag"),
                FieldSpec("current_status", "str", "Current customer-visible status", index="tag"),
                FieldSpec("started_at", "str", "Incident start timestamp"),
                FieldSpec("updated_at", "str", "Most recent status update timestamp"),
                FieldSpec("next_update_due", "str | None", "When the next public update is expected"),
                FieldSpec("affected_capabilities", "list[str]", "Capabilities affected by the incident"),
                FieldSpec("public_message", "str", "Customer-facing service status message", index="text"),
            ),
        ),
        EntitySpec(
            class_name="SupportGuidanceDoc",
            redis_key_template=f"{namespace_prefix}_support_guidance_doc:{{doc_id}}",
            file_name="support_guidance_docs.jsonl",
            id_field="doc_id",
            fields=(
                FieldSpec("doc_id", "str", "Unique guidance document identifier", is_key_component=True),
                FieldSpec("category", "str", "Guidance topic category", index="tag"),
                FieldSpec("title", "str", "Guidance title", index="text", weight=2.0),
                FieldSpec("content", "str", "Guidance content", index="text"),
                FieldSpec(
                    "content_embedding",
                    "list[float]",
                    "Vector embedding for the document content",
                    index="vector",
                    vector_dim=1536,
                    distance_metric="cosine",
                ),
            ),
        ),
    )
