"""Sports betting data-model definitions."""

from __future__ import annotations

from backend.app.core.domain_schema import (
    EntitySpec,
    FieldSpec,
    RelationshipSpec,
    entity_by_class,
    entity_by_file,
)


ENTITY_SPECS: tuple[EntitySpec, ...] = (
    EntitySpec(
        class_name="Player",
        redis_key_template="sports_betting_player:{player_id}",
        file_name="players.jsonl",
        id_field="player_id",
        fields=(
            FieldSpec("player_id", "str", "Unique player identifier", is_key_component=True),
            FieldSpec("name", "str", "Player full name", index="text", weight=2.0),
            FieldSpec("email", "str", "Player email", index="text", weight=1.5, no_stem=True),
            FieldSpec("phone", "str | None", "Phone number"),
            FieldSpec("account_status", "str", "Account status: active, suspended, self_excluded", index="tag"),
            FieldSpec("kyc_status", "str", "KYC status: verified, pending, review_required", index="tag"),
            FieldSpec("home_jurisdiction", "str", "Regulated market or country for the player", index="tag"),
            FieldSpec("preferred_sports", "str", "Comma-separated preferred sports", index="text"),
            FieldSpec("responsible_gaming_level", "str", "Safer gambling profile: standard, watch, protected", index="tag"),
            FieldSpec("deposit_limit_weekly", "float", "Weekly deposit limit in account currency", index="numeric"),
            FieldSpec("account_created_at", "str", "ISO timestamp of account creation"),
        ),
        relationships=(
            RelationshipSpec("bets", "Bets placed by this player", "player_id", "list[Bet]"),
            RelationshipSpec("wallet_transactions", "Wallet transactions for this player", "player_id", "list[WalletTransaction]"),
        ),
    ),
    EntitySpec(
        class_name="SportEvent",
        redis_key_template="sports_betting_event:{event_id}",
        file_name="sport_events.jsonl",
        id_field="event_id",
        fields=(
            FieldSpec("event_id", "str", "Unique sport event identifier", is_key_component=True),
            FieldSpec("sport", "str", "Sport name", index="tag"),
            FieldSpec("league", "str", "Competition or league", index="tag"),
            FieldSpec("event_name", "str", "Event display name", index="text", weight=2.0),
            FieldSpec("start_time", "str", "ISO timestamp when the event starts"),
            FieldSpec("status", "str", "Event status: scheduled, live, final, abandoned", index="tag"),
            FieldSpec("score", "str | None", "Current or final score/result", index="text"),
            FieldSpec("venue", "str | None", "Venue or track"),
        ),
        relationships=(
            RelationshipSpec("markets", "Betting markets offered for this event", "event_id", "list[Market]"),
        ),
    ),
    EntitySpec(
        class_name="Market",
        redis_key_template="sports_betting_market:{market_id}",
        file_name="markets.jsonl",
        id_field="market_id",
        fields=(
            FieldSpec("market_id", "str", "Unique market identifier", is_key_component=True),
            FieldSpec("event_id", "str", "Related sport event", index="tag"),
            FieldSpec("market_type", "str", "Market type: match_winner, total_goals, both_teams_to_score, each_way", index="tag"),
            FieldSpec("selection_name", "str", "Selection or runner name", index="text", weight=1.5),
            FieldSpec("odds_decimal", "float", "Current decimal odds", index="numeric", sortable=True),
            FieldSpec("market_status", "str", "Market status: open, suspended, settled, void", index="tag"),
            FieldSpec("result", "str | None", "Result for this market: won, lost, void, pending", index="tag"),
            FieldSpec("last_price_move_at", "str | None", "ISO timestamp of latest odds update"),
            FieldSpec("trading_note", "str | None", "Trading desk note or reason for current market status", index="text"),
        ),
        relationships=(
            RelationshipSpec("event", "Sport event for this market", "event_id", "SportEvent"),
        ),
    ),
    EntitySpec(
        class_name="Bet",
        redis_key_template="sports_betting_bet:{bet_id}",
        file_name="bets.jsonl",
        id_field="bet_id",
        fields=(
            FieldSpec("bet_id", "str", "Unique bet identifier", is_key_component=True),
            FieldSpec("player_id", "str", "Player who placed the bet", index="tag"),
            FieldSpec("bet_type", "str", "Bet type: single, accumulator, each_way", index="tag"),
            FieldSpec("status", "str", "Bet status: open, won, lost, void, pending_settlement, cashed_out", index="tag"),
            FieldSpec("stake", "float", "Stake amount", index="numeric", sortable=True),
            FieldSpec("potential_return", "float", "Maximum possible return", index="numeric", sortable=True),
            FieldSpec("placed_at", "str", "ISO timestamp when the bet was placed"),
            FieldSpec("settled_at", "str | None", "ISO timestamp when the bet settled"),
            FieldSpec("channel", "str", "Bet channel: mobile, web, retail", index="tag"),
            FieldSpec("currency", "str", "Account currency", index="tag"),
            FieldSpec("cashout_available", "bool", "Whether cash out is currently available"),
            FieldSpec("cashout_value", "float | None", "Current cash-out value if available", index="numeric"),
            FieldSpec("risk_flag", "str", "Risk flag: none, affordability_review, integrity_review, responsible_gaming", index="tag"),
            FieldSpec("summary", "str", "Human-readable bet summary", index="text"),
        ),
        relationships=(
            RelationshipSpec("player", "Player who placed the bet", "player_id", "Player"),
            RelationshipSpec("legs", "Individual selections for this bet", "bet_id", "list[BetLeg]"),
            RelationshipSpec("settlement_events", "Settlement timeline for this bet", "bet_id", "list[BetSettlementEvent]"),
        ),
    ),
    EntitySpec(
        class_name="BetLeg",
        redis_key_template="sports_betting_bet_leg:{leg_id}",
        file_name="bet_legs.jsonl",
        id_field="leg_id",
        fields=(
            FieldSpec("leg_id", "str", "Unique bet-leg identifier", is_key_component=True),
            FieldSpec("bet_id", "str", "Parent bet", index="tag"),
            FieldSpec("event_id", "str", "Related sport event", index="tag"),
            FieldSpec("market_id", "str", "Related market", index="tag"),
            FieldSpec("event_name", "str", "Denormalized event display name", index="text"),
            FieldSpec("market_type", "str", "Market type for this selection", index="tag"),
            FieldSpec("selection_name", "str", "Selection chosen by the player", index="text"),
            FieldSpec("odds_decimal", "float", "Accepted decimal odds", index="numeric"),
            FieldSpec("leg_status", "str", "Leg status: open, won, lost, void, pending", index="tag"),
            FieldSpec("result_detail", "str | None", "Result explanation for the leg", index="text"),
        ),
        relationships=(
            RelationshipSpec("bet", "Parent bet", "bet_id", "Bet"),
            RelationshipSpec("event", "Related event", "event_id", "SportEvent"),
            RelationshipSpec("market", "Related market", "market_id", "Market"),
        ),
    ),
    EntitySpec(
        class_name="BetSettlementEvent",
        redis_key_template="sports_betting_settlement_event:{settlement_event_id}",
        file_name="bet_settlement_events.jsonl",
        id_field="settlement_event_id",
        fields=(
            FieldSpec("settlement_event_id", "str", "Unique settlement timeline event identifier", is_key_component=True),
            FieldSpec("bet_id", "str", "Associated bet", index="tag"),
            FieldSpec("event_type", "str", "Timeline event type: placed, event_final, result_received, review_started, bet_settled, payout_credited", index="tag"),
            FieldSpec("timestamp", "str", "ISO timestamp of the event"),
            FieldSpec("description", "str", "Human-readable settlement event description", index="text"),
            FieldSpec("actor", "str", "Who triggered it: player, trading, feed, system, support", index="tag"),
        ),
        relationships=(
            RelationshipSpec("bet", "Associated bet", "bet_id", "Bet"),
        ),
    ),
    EntitySpec(
        class_name="WalletTransaction",
        redis_key_template="sports_betting_wallet_transaction:{transaction_id}",
        file_name="wallet_transactions.jsonl",
        id_field="transaction_id",
        fields=(
            FieldSpec("transaction_id", "str", "Unique wallet transaction identifier", is_key_component=True),
            FieldSpec("player_id", "str", "Player who owns the wallet transaction", index="tag"),
            FieldSpec("bet_id", "str | None", "Related bet when applicable", index="tag"),
            FieldSpec("transaction_type", "str", "Transaction type: deposit, stake, payout, refund, withdrawal", index="tag"),
            FieldSpec("amount", "float", "Signed transaction amount", index="numeric", sortable=True),
            FieldSpec("balance_after", "float", "Wallet balance after the transaction", index="numeric", sortable=True),
            FieldSpec("status", "str", "Transaction status: pending, completed, failed, held", index="tag"),
            FieldSpec("created_at", "str", "ISO timestamp of transaction creation"),
            FieldSpec("payment_method", "str | None", "Payment method or wallet rail", index="tag"),
            FieldSpec("processor_reference", "str | None", "Processor or ledger reference", index="tag"),
        ),
        relationships=(
            RelationshipSpec("player", "Player who owns the transaction", "player_id", "Player"),
            RelationshipSpec("bet", "Related bet", "bet_id", "Bet"),
        ),
    ),
    EntitySpec(
        class_name="SupportTicket",
        redis_key_template="sports_betting_support_ticket:{ticket_id}",
        file_name="support_tickets.jsonl",
        id_field="ticket_id",
        fields=(
            FieldSpec("ticket_id", "str", "Unique support ticket identifier", is_key_component=True),
            FieldSpec("player_id", "str", "Player who filed the ticket", index="tag"),
            FieldSpec("bet_id", "str | None", "Related bet", index="tag"),
            FieldSpec("category", "str", "Category: settlement_delay, cashout, account, payment, responsible_gaming", index="tag"),
            FieldSpec("status", "str", "Ticket status: open, in_progress, resolved, closed", index="tag"),
            FieldSpec("created_at", "str", "ISO timestamp when ticket was created"),
            FieldSpec("resolved_at", "str | None", "ISO timestamp when resolved"),
            FieldSpec("summary", "str", "Ticket summary", index="text"),
            FieldSpec("resolution", "str | None", "How it was resolved"),
        ),
        relationships=(
            RelationshipSpec("player", "Player who filed the ticket", "player_id", "Player"),
            RelationshipSpec("bet", "Related bet", "bet_id", "Bet"),
        ),
    ),
    EntitySpec(
        class_name="Policy",
        redis_key_template="sports_betting_policy:{policy_id}",
        file_name="policies.jsonl",
        id_field="policy_id",
        fields=(
            FieldSpec("policy_id", "str", "Unique policy identifier", is_key_component=True),
            FieldSpec("title", "str", "Policy title", index="text", weight=2.0),
            FieldSpec("category", "str", "Policy category", index="tag"),
            FieldSpec("content", "str", "Full policy text", index="text"),
            FieldSpec(
                "content_embedding",
                "list[float]",
                "Vector embedding of policy content",
                index="vector",
                vector_dim=1536,
                distance_metric="cosine",
            ),
        ),
    ),
)

ENTITY_BY_FILE = entity_by_file(ENTITY_SPECS)
ENTITY_BY_CLASS = entity_by_class(ENTITY_SPECS)
