"""Generate JSONL (smoke tests) and SQL (Postgres/RDI source of truth) for meeting-intel."""

from __future__ import annotations

import hashlib
import importlib.util
import json
from pathlib import Path
from typing import Any

from backend.app.core.domain_contract import GeneratedDataset

ROOT = Path(__file__).resolve().parents[2]
DOMAIN_DIR = Path(__file__).resolve().parent
SQL_DIR = DOMAIN_DIR / "rdi" / "source-db" / "scripts"
FILE_MAP = {
    "Project": "projects.jsonl",
    "Person": "people.jsonl",
    "Meeting": "meetings.jsonl",
    "MeetingParticipant": "meeting_participants.jsonl",
    "TranscriptSegment": "transcripts.jsonl",
    "Decision": "decisions.jsonl",
    "ActionItem": "action_items.jsonl",
    "Risk": "risks.jsonl",
    "ProjectDependency": "project_dependencies.jsonl",
    "Agenda": "agendas.jsonl",
}


def _load(name: str, file_name: str):
    path = DOMAIN_DIR / file_name
    spec = importlib.util.spec_from_file_location(f"meeting_intel_{name}", path)
    if spec is None or spec.loader is None:
        raise ImportError(path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def fake_embedding(text: str, dim: int = 1536) -> list[float]:
    digest = hashlib.sha256(text.encode("utf-8")).digest()
    vals = []
    seed = digest
    while len(vals) < dim:
        seed = hashlib.sha256(seed).digest()
        for b in seed:
            vals.append((b / 255.0) * 2 - 1)
            if len(vals) >= dim:
                break
    return vals[:dim]


def _sql_str(value: Any) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    text = str(value).replace("'", "''")
    return f"'{text}'"


def _sql_json(value: Any) -> str:
    if value is None or value == "":
        return "NULL"
    if isinstance(value, (dict, list)):
        raw = json.dumps(value, ensure_ascii=False)
    else:
        raw = str(value)
    return f"{_sql_str(raw)}::jsonb"


def _participants(attendees: dict[str, list[str]]) -> list[dict[str, Any]]:
    rows = []
    for meeting_id, people in attendees.items():
        for person_id in people:
            rows.append(
                {
                    "participant_id": f"part-{meeting_id}-{person_id}",
                    "meeting_id": meeting_id,
                    "person_id": person_id,
                }
            )
    return rows


def _with_embeddings(meetings, transcripts, decisions, risks):
    for row in meetings:
        row["summary_embedding"] = fake_embedding(row.get("summary") or row["title"])
    for row in transcripts:
        row["text_embedding"] = fake_embedding(row["text"])
    for row in decisions:
        row["text_embedding"] = fake_embedding(row["text"])
    for row in risks:
        row["text_embedding"] = fake_embedding(row["text"])


def _write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("".join(json.dumps(r, ensure_ascii=False) + "\n" for r in rows), encoding="utf-8")


def _seed_sql(dataset: dict[str, list[dict[str, Any]]]) -> str:
    lines = [
        "-- Idempotent meeting-intel seed. Generated by domains/meeting-intel/data_generator.py",
        "BEGIN;",
        "TRUNCATE TABLE agendas, project_dependencies, risks, action_items, decisions,",
        "  transcripts, meeting_participants, meetings, people, projects CASCADE;",
        "",
    ]
    for p in dataset["Person"]:
        lines.append(
            "INSERT INTO people (person_id, name, role, team, email, access_role) VALUES ("
            f"{_sql_str(p['person_id'])}, {_sql_str(p['name'])}, {_sql_str(p['role'])}, "
            f"{_sql_str(p['team'])}, {_sql_str(p['email'])}, {_sql_str(p['access_role'])});"
        )
    lines.append("")
    for p in dataset["Project"]:
        lines.append(
            "INSERT INTO projects (project_id, name, status, team, lead_person_id, target_date, summary) VALUES ("
            f"{_sql_str(p['project_id'])}, {_sql_str(p['name'])}, {_sql_str(p['status'])}, "
            f"{_sql_str(p['team'])}, {_sql_str(p['lead_person_id'])}, {_sql_str(p['target_date'])}::date, "
            f"{_sql_str(p['summary'])});"
        )
    lines.append("")
    for m in dataset["Meeting"]:
        lines.append(
            "INSERT INTO meetings (meeting_id, project_id, title, meeting_date, kind, status, summary, visibility) VALUES ("
            f"{_sql_str(m['meeting_id'])}, {_sql_str(m['project_id'])}, {_sql_str(m['title'])}, "
            f"{_sql_str(m['meeting_date'])}::date, {_sql_str(m['kind'])}, {_sql_str(m['status'])}, "
            f"{_sql_str(m['summary'])}, {_sql_str(m['visibility'])});"
        )
    lines.append("")
    for r in dataset["MeetingParticipant"]:
        lines.append(
            "INSERT INTO meeting_participants (participant_id, meeting_id, person_id) VALUES ("
            f"{_sql_str(r['participant_id'])}, {_sql_str(r['meeting_id'])}, {_sql_str(r['person_id'])});"
        )
    lines.append("")
    for r in dataset["TranscriptSegment"]:
        lines.append(
            "INSERT INTO transcripts (transcript_id, meeting_id, segment_id, start_ts, speaker_person_id, text) VALUES ("
            f"{_sql_str(r['transcript_id'])}, {_sql_str(r['meeting_id'])}, {_sql_str(r['segment_id'])}, "
            f"{_sql_str(r['start_ts'])}, {_sql_str(r['speaker_person_id'])}, {_sql_str(r['text'])});"
        )
    lines.append("")
    for r in dataset["Decision"]:
        lines.append(
            "INSERT INTO decisions (decision_id, meeting_id, project_id, text, decided_at, status, "
            "superseded_by_decision_id, source_segment_id, visibility) VALUES ("
            f"{_sql_str(r['decision_id'])}, {_sql_str(r['meeting_id'])}, {_sql_str(r['project_id'])}, "
            f"{_sql_str(r['text'])}, {_sql_str(r['decided_at'])}::date, {_sql_str(r['status'])}, "
            f"NULL, {_sql_str(r['source_segment_id'])}, "
            f"{_sql_str(r['visibility'])});"
        )
    for r in dataset["Decision"]:
        if r.get("superseded_by_decision_id"):
            lines.append(
                "UPDATE decisions SET superseded_by_decision_id = "
                f"{_sql_str(r['superseded_by_decision_id'])} WHERE decision_id = {_sql_str(r['decision_id'])};"
            )
    lines.append("")
    for r in dataset["ActionItem"]:
        lines.append(
            "INSERT INTO action_items (action_id, meeting_id, project_id, owner_person_id, text, status, "
            "due_date, created_at, updated_at, source_segment_id, visibility) VALUES ("
            f"{_sql_str(r['action_id'])}, {_sql_str(r['meeting_id'])}, {_sql_str(r['project_id'])}, "
            f"{_sql_str(r['owner_person_id'])}, {_sql_str(r['text'])}, {_sql_str(r['status'])}, "
            f"{_sql_str(r['due_date'])}::date, {_sql_str(r['created_at'])}::timestamptz, "
            f"{_sql_str(r['updated_at'])}::timestamptz, {_sql_str(r['source_segment_id'])}, "
            f"{_sql_str(r['visibility'])});"
        )
    lines.append("")
    for r in dataset["Risk"]:
        lines.append(
            "INSERT INTO risks (risk_id, project_id, meeting_id, text, severity, status, source_segment_id, visibility) VALUES ("
            f"{_sql_str(r['risk_id'])}, {_sql_str(r['project_id'])}, {_sql_str(r['meeting_id'])}, "
            f"{_sql_str(r['text'])}, {_sql_str(r['severity'])}, {_sql_str(r['status'])}, "
            f"{_sql_str(r['source_segment_id'])}, {_sql_str(r['visibility'])});"
        )
    lines.append("")
    for r in dataset["ProjectDependency"]:
        blocking = "TRUE" if str(r["blocking"]).lower() == "true" else "FALSE"
        lines.append(
            "INSERT INTO project_dependencies (dependency_id, project_id, depends_on_project_id, description, blocking) VALUES ("
            f"{_sql_str(r['dependency_id'])}, {_sql_str(r['project_id'])}, {_sql_str(r['depends_on_project_id'])}, "
            f"{_sql_str(r['description'])}, {blocking});"
        )
    lines.append("")
    for r in dataset["Agenda"]:
        lines.append(
            "INSERT INTO agendas (agenda_id, meeting_id, human_agenda, ai_agenda, ai_agenda_sources, "
            "generated_at, generated_by, status, visibility) VALUES ("
            f"{_sql_str(r['agenda_id'])}, {_sql_str(r['meeting_id'])}, {_sql_str(r['human_agenda'])}, "
            f"{_sql_str(r['ai_agenda'])}, {_sql_json(r['ai_agenda_sources'])}, "
            f"{_sql_str(r['generated_at'])}{'::timestamptz' if r['generated_at'] else ''}, "
            f"{_sql_str(r['generated_by'])}, {_sql_str(r['status'])}, {_sql_str(r['visibility'])});"
        )
    lines.append("COMMIT;")
    lines.append("")
    return "\n".join(lines)


def extra_transcript_sql() -> str:
    """Held-out transcript for live extract_from_transcript. Not in the default seed."""
    return """-- Held-out transcript for live extraction (Section 6). Not in 01-seed.sql.
BEGIN;
INSERT INTO meetings (meeting_id, project_id, title, meeting_date, kind, status, summary, visibility)
VALUES (
  'mtg-2026-09-01-pipeline-extra', 'proj-pipeline', 'Pipeline ad-hoc extraction dry-run',
  '2026-09-01', 'sync', 'held',
  'Held-out transcript used to demo live extract_from_transcript.', 'team'
)
ON CONFLICT (meeting_id) DO NOTHING;

INSERT INTO meeting_participants (participant_id, meeting_id, person_id) VALUES
  ('part-mtg-2026-09-01-pipeline-extra-person-chris', 'mtg-2026-09-01-pipeline-extra', 'person-chris'),
  ('part-mtg-2026-09-01-pipeline-extra-person-jordan', 'mtg-2026-09-01-pipeline-extra', 'person-jordan')
ON CONFLICT (participant_id) DO NOTHING;

INSERT INTO transcripts (transcript_id, meeting_id, segment_id, start_ts, speaker_person_id, text) VALUES
  ('tr-extra-01', 'mtg-2026-09-01-pipeline-extra', 'seg-extra-01', '00:00:10', 'person-chris',
   'This is a held-out pipeline working session. We decided to delay payments CDC until PII tags ship.'),
  ('tr-extra-02', 'mtg-2026-09-01-pipeline-extra', 'seg-extra-02', '00:01:00', 'person-jordan',
   'Action: Chris will file the PII tag spreadsheet by September 12. I will warn compliance if it slips.'),
  ('tr-extra-03', 'mtg-2026-09-01-pipeline-extra', 'seg-extra-03', '00:02:10', 'person-chris',
   'Risk: if payments CDC goes live without tags we will fail the SOC2 sample.'),
  ('tr-extra-04', 'mtg-2026-09-01-pipeline-extra', 'seg-extra-04', '00:03:00', 'person-jordan',
   'Decision: do not enable the payments connector in production this month.'),
  ('tr-extra-05', 'mtg-2026-09-01-pipeline-extra', 'seg-extra-05', '00:03:40', 'person-chris',
   'I will also add a lineage stub page so extract_from_transcript has a fourth follow-up.')
ON CONFLICT (transcript_id) DO NOTHING;
COMMIT;
"""


def build_dataset() -> dict[str, list[dict[str, Any]]]:
    seed = _load("seed", "seed.py")
    transcripts_mod = _load("transcripts", "transcripts.py")
    meetings = [dict(r) for r in seed.MEETINGS]
    transcripts = [dict(r) for r in transcripts_mod.TRANSCRIPTS]
    decisions = [dict(r) for r in seed.DECISIONS]
    risks = [dict(r) for r in seed.RISKS]
    _with_embeddings(meetings, transcripts, decisions, risks)
    return {
        "Person": list(seed.PEOPLE),
        "Project": list(seed.PROJECTS),
        "Meeting": meetings,
        "MeetingParticipant": _participants(seed.ATTENDEES),
        "TranscriptSegment": transcripts,
        "Decision": decisions,
        "ActionItem": list(seed.ACTIONS),
        "Risk": risks,
        "ProjectDependency": list(seed.DEPENDENCIES),
        "Agenda": list(seed.AGENDAS),
    }


def generate_demo_data(*, output_dir: Path, seed: int | None = None, update_env_file: bool = False) -> GeneratedDataset:
    del seed
    dataset = build_dataset()
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    for class_name, file_name in FILE_MAP.items():
        _write_jsonl(output_dir / file_name, dataset[class_name])

    SQL_DIR.mkdir(parents=True, exist_ok=True)
    (SQL_DIR / "01-seed.sql").write_text(_seed_sql(dataset), encoding="utf-8")
    extra_dir = SQL_DIR / "extra"
    extra_dir.mkdir(parents=True, exist_ok=True)
    (extra_dir / "transcript-05.sql").write_text(extra_transcript_sql(), encoding="utf-8")

    # Always return identity env updates. scripts/generate_data.py writes them
    # when invoked; tests pass update_env_file=False so they do not touch .env.
    del update_env_file
    env_updates = {
        "DEMO_USER_ID": "person-maya",
        "DEMO_USER_NAME": "Maya Chen",
        "DEMO_USER_EMAIL": "maya.chen@harborline.example",
        "DEMO_USER_ROLE": "team",
        "DEMO_DOMAIN": "meeting-intel",
    }

    summary = {key: len(rows) for key, rows in dataset.items()}
    return GeneratedDataset(output_dir=str(output_dir), env_updates=env_updates, summary=summary)


if __name__ == "__main__":
    generate_demo_data(output_dir=ROOT / "output" / "meeting-intel", update_env_file=True)
