"""Hand-authored transcripts. Segment ids are cited by seed decisions/actions/risks."""

from __future__ import annotations

from typing import Any


def _seg(meeting_id: str, segment_id: str, start_ts: str, speaker: str, text: str) -> dict[str, Any]:
    return {
        "transcript_id": f"tr-{meeting_id}-{segment_id}",
        "meeting_id": meeting_id,
        "segment_id": segment_id,
        "start_ts": start_ts,
        "speaker_person_id": speaker,
        "text": text,
    }


PLATFORM_SEP4: list[dict[str, Any]] = [
    _seg("mtg-2026-09-04-platform", "seg-plat-01", "00:00:12", "person-jordan", "Welcome back. This is the Platform weekly for September 4. Maya, Priya, and Sam from Mobile is sitting in because they are blocked on us."),
    _seg("mtg-2026-09-04-platform", "seg-plat-02", "00:00:40", "person-maya", "Thanks Sam. I want this meeting to be honest. We are not green. Dual-write is still slow, the runbook is not done, and Legal has not signed the identity SLA."),
    _seg("mtg-2026-09-04-platform", "seg-plat-03", "00:01:15", "person-sam", "Mobile is date-locked to October 15. We reversed the November delay last month. If identity is not ready we ship a store listing that cannot log people in."),
    _seg("mtg-2026-09-04-platform", "seg-plat-04", "00:01:52", "person-jordan", "Understood. Let's walk the three overdue items first, then Q4 dates, then whether Sam keeps coming to this forum."),
    _seg("mtg-2026-09-04-platform", "seg-plat-05", "00:02:20", "person-maya", "Item one is the cutover runbook. I outlined it in July but rollback and dual-write drain are still placeholders. I missed the September 1 due date."),
    _seg("mtg-2026-09-04-platform", "seg-plat-06", "00:02:58", "person-maya", "I am taking the action to finish the cutover runbook including rollback and dual-write drain. Until that exists we should treat cutover as high risk."),
    _seg("mtg-2026-09-04-platform", "seg-plat-07", "00:03:30", "person-maya", "Related: I also missed checking the rollback script against last week's snapshot. That is overdue as of yesterday."),
    _seg("mtg-2026-09-04-platform", "seg-plat-08", "00:04:05", "person-jordan", "Are we silently slipping October 15? Dana will ask on Monday."),
    _seg("mtg-2026-09-04-platform", "seg-plat-09", "00:04:22", "person-maya", "No. Decision: keep the Platform cutover target of 15 October. No silent date slip. We burn down the overdues."),
    _seg("mtg-2026-09-04-platform", "seg-plat-10", "00:04:55", "person-priya", "Item two is dual-write lag. Staging p95 is still around four seconds with production-sized payloads. The action to get under two seconds was due September 2 and it is overdue. That is on me."),
    _seg("mtg-2026-09-04-platform", "seg-plat-11", "00:05:40", "person-priya", "Risk: if we launch Mobile on a four second dual-write, sessions will desync. Users will look logged in on one device and logged out on the other."),
    _seg("mtg-2026-09-04-platform", "seg-plat-12", "00:06:10", "person-sam", "That matches what we saw in contract tests this week. We will keep tests running but we will not enable login flags."),
    _seg("mtg-2026-09-04-platform", "seg-plat-13", "00:06:38", "person-jordan", "Item three is the SLA. I introduced Legal in July. The signature was due September 3. Still sitting in their queue."),
    _seg("mtg-2026-09-04-platform", "seg-plat-14", "00:07:05", "person-jordan", "I will chase Legal personally this afternoon. Action remains: get Legal signature on the identity service SLA. Overdue."),
    _seg("mtg-2026-09-04-platform", "seg-plat-15", "00:07:32", "person-sam", "Without that signature we cannot put an uptime sentence in the store listing. Call that a high risk for Mobile too."),
    _seg("mtg-2026-09-04-platform", "seg-plat-16", "00:08:00", "person-jordan", "Reminder of history so nobody re-litigates it: we picked Auth0 in July, then reversed to in-house identity in August. We are not going back to Auth0 in this room."),
    _seg("mtg-2026-09-04-platform", "seg-plat-17", "00:08:35", "person-maya", "Correct. In-house is the current decision. The old Auth0 decision is superseded."),
    _seg("mtg-2026-09-04-platform", "seg-plat-18", "00:09:00", "person-jordan", "Decision: Sam joins Platform weekly until the blocking identity work clears. Sam, does that work?"),
    _seg("mtg-2026-09-04-platform", "seg-plat-19", "00:09:18", "person-sam", "Yes. I would rather sit here than discover slippage in Slack."),
    _seg("mtg-2026-09-04-platform", "seg-plat-20", "00:09:40", "person-maya", "New action for me: add SRE to the dual-write paging rotation by September 11."),
    _seg("mtg-2026-09-04-platform", "seg-plat-21", "00:10:08", "person-priya", "I still owe the production-sized lag reproduction. That was due September 5, so it is about to flip overdue if I do not finish tomorrow."),
    _seg("mtg-2026-09-04-platform", "seg-plat-22", "00:10:40", "person-priya", "I will also confirm Redis and Postgres capacity for dual-write peak by the 13th."),
    _seg("mtg-2026-09-04-platform", "seg-plat-23", "00:11:10", "person-jordan", "Hiring: we cannot talk headcount in this forum. Cover the on-call with current staff. Next week's human agenda is migration status, Q4 dates, hiring coverage at a high level."),
    _seg("mtg-2026-09-04-platform", "seg-plat-24", "00:11:45", "person-maya", "If next week's AI agenda is useful, group by owner and put the overdue runbook, dual-write, and SLA first. That is what Mobile actually needs."),
    _seg("mtg-2026-09-04-platform", "seg-plat-25", "00:12:15", "person-sam", "Please cite the action ids when you send notes. I will paste them into the Mobile RAID log."),
    _seg("mtg-2026-09-04-platform", "seg-plat-26", "00:12:40", "person-jordan", "Wrapping. Three overdues, October 15 stays, Sam is in this forum, no Auth0 revival. Thanks everyone."),
    _seg("mtg-2026-09-04-platform", "seg-plat-27", "00:13:05", "person-maya", "Before we drop: I want the AI agenda for next week to list overdue items first, grouped by owner. Mine are the runbook and the rollback script. Priya has dual-write lag and capacity. Jordan has the SLA. That grouping is how I actually work the board."),
    _seg("mtg-2026-09-04-platform", "seg-plat-28", "00:13:45", "person-priya", "Dual-write context for the notes. We write identity to the monolith and the new service in the same request. p95 in staging with production-sized payloads is still about four seconds. The action to get under two seconds was due September 2. It is overdue. Mobile session refresh fails when that lag shows up."),
    _seg("mtg-2026-09-04-platform", "seg-plat-29", "00:14:30", "person-jordan", "Legal received the identity SLA template at the end of July. I pinged them twice. The signature was due September 3. Without it Sam cannot put an uptime sentence in the store listing. That is why Mobile is blocked on us, not because they are slow."),
    _seg("mtg-2026-09-04-platform", "seg-plat-30", "00:15:10", "person-sam", "I will paste the three action ids into the Mobile RAID log tonight: runbook, dual-write, SLA. If Minutes drafts an agenda, cite those ids. Do not revive the July Auth0 decision. Do not revive the July schema freeze. Both were reversed on August 13."),
    _seg("mtg-2026-09-04-platform", "seg-plat-31", "00:15:50", "person-maya", "History for the transcript so retrieval has it: July 2 we chose Auth0 as interim identity. August 13 we reversed that and committed to in-house. July 16 we froze orders schema. August 13 we lifted the freeze so Mobile contract tests could land. Current decisions are in-house identity and unfrozen schema. The old rows are superseded."),
    _seg("mtg-2026-09-04-platform", "seg-plat-32", "00:16:40", "person-jordan", "Hiring coverage on the human agenda is high-level only. We cover on-call with current staff. We are not discussing headcount in this forum. Next week's upcoming meeting is mtg-2026-09-09-platform. Human agenda is already three lines: migration status, Q4 dates, hiring coverage."),
    _seg("mtg-2026-09-04-platform", "seg-plat-33", "00:17:20", "person-priya", "I still owe a reproduction of the four second lag with production-sized payloads. That flipped overdue around September 5. I also owe Redis and Postgres capacity confirmation by the 13th so we do not dual-write ourselves into a disk incident."),
    _seg("mtg-2026-09-04-platform", "seg-plat-34", "00:18:00", "person-maya", "Rollback script check is overdue as of September 6. I will treat that as part of the runbook, but it is a separate action so it does not hide. Cutover without a finished runbook has no tested rollback. That is a high risk."),
    _seg("mtg-2026-09-04-platform", "seg-plat-35", "00:18:40", "person-sam", "Mobile will keep login flags dark and will not submit store metadata. We are date-locked to October 15 and blocked on platform identity. That is the program risk in one sentence. Thank you for letting me sit here."),
]

MOBILE_SEP3: list[dict[str, Any]] = [
    _seg("mtg-2026-09-03-mobile", "seg-mob-01", "00:00:08", "person-alex", "Mobile weekly, September 3. Sam, Maya is here from Platform so we can talk the blocker in person."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-02", "00:00:32", "person-sam", "Quick history because people still quote July Slack. On July 8 we decided to delay launch to November 12."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-03", "00:00:58", "person-alex", "And on August 12 we reversed that. Current decision is keep October 15. The November delay is superseded. If anyone asks 'did we delay', the answer is no, not anymore."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-04", "00:01:30", "person-maya", "I agree with that reading. Platform did not ask you to move the date again."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-05", "00:01:48", "person-sam", "Feature work is actually fine. New home, wallet, and biometric unlock are behind flags. QA matrix on iOS 18 and Android 15 is done."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-06", "00:02:20", "person-alex", "Store listing copy is locked. What we cannot do is submit."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-07", "00:02:42", "person-sam", "Login against migrated identity still fails when dual-write lags. Contract tests are red on session refresh."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-08", "00:03:15", "person-sam", "Risk: we are date-locked to October 15 and blocked on platform identity. That is the whole program risk in one sentence."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-09", "00:03:48", "person-alex", "Someone in marketing asked if we can ship a partial login on the old monolith. I want a hard no."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-10", "00:04:10", "person-maya", "Hard no from Platform too. Dual-write exists so we do not grow the monolith."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-11", "00:04:28", "person-sam", "Decision: do not ship a partial login on the old monolith; wait for migrated identity."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-12", "00:04:55", "person-alex", "Good. I will tell marketing."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-13", "00:05:12", "person-sam", "Flags stay dark. Even internal dogfood login stays off until Maya says green."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-14", "00:05:35", "person-sam", "Decision: keep feature flags dark until platform identity is green; do not enable store rollout. Action on me to hold those flags."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-15", "00:06:05", "person-alex", "And I will hold App Store and Play metadata. We do not submit."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-16", "00:06:28", "person-alex", "Risk if we submit early: we advertise a login that does not work. Action is mine, due mid-September."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-17", "00:06:55", "person-maya", "The three things you are waiting on from us are the runbook, dual-write under two seconds, and the signed SLA. Those are already overdue on the Platform board."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-18", "00:07:28", "person-sam", "I will join your weekly until those clear. Thanks for the invite."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-19", "00:07:48", "person-alex", "Portal keeps asking if they are blocked. Directly they depend on us; transitively they depend on you. We should not over-claim."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-20", "00:08:20", "person-sam", "I will keep identity contract tests running against staging even while blocked, due next week."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-21", "00:08:50", "person-maya", "I will be at Platform weekly tomorrow with the same three overdues. Please send Sam if I miss a nuance."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-22", "00:09:15", "person-alex", "Human agenda for next week: launch date, platform blocker, store hold. If Minutes drafts an AI agenda, cite the current October 15 decision, not the July delay."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-23", "00:09:50", "person-sam", "Agreed. Latest valid information is keep the date. The delay is historical."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-24", "00:10:12", "person-alex", "Closing. We are blocked, we are not delayed, flags stay dark, no monolith login."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-25", "00:10:35", "person-sam", "I want the latest-valid-information path to be checkable. July 8 decision delayed launch to November 12. August 12 reversed it: keep October 15 and treat platform dual-write as a burn-down, not a date change. If someone asks 'did we delay', the answer is no, not anymore. Cite the superseding decision."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-26", "00:11:20", "person-alex", "Marketing still has a November draft in a folder. I already sent the correction. Please do not re-introduce November in any agenda Minutes generates. The current decision is October 15. The July delay is historical and superseded."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-27", "00:12:00", "person-maya", "The three Platform overdues you are waiting on are Maya's cutover runbook, Priya's dual-write p95 under two seconds, and Jordan's signed identity SLA. Those explain why Mobile is blocked. Portal is not in this meeting; they depend on you, not directly on us."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-28", "00:12:45", "person-sam", "Hard no on partial login against the old monolith. Dual-write exists so we do not grow the monolith. Feature flags stay dark, including internal dogfood login, until Maya says identity is green. I own that action."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-29", "00:13:25", "person-alex", "I own the store hold. We do not submit App Store or Play metadata while login cannot work. Premature submit would advertise a login that does not work. That risk stays open."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-30", "00:14:00", "person-sam", "Contract tests against staging stay on even while we are blocked. I would rather see a red session-refresh every night than discover it on October 14. Due next week."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-31", "00:14:35", "person-alex", "Human agenda for September 10: launch date, platform blocker, store hold. If Minutes drafts an AI agenda, put the current October 15 decision first, then the three Platform overdues with owners, then the flag and store holds."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-32", "00:15:15", "person-maya", "I will be at Platform weekly tomorrow with the same three overdues. Sam is invited until the blocking identity work clears. Please send him if I miss a nuance about store listing language."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-33", "00:15:50", "person-alex", "I also want a sentence in the notes about Portal. They depend on our session SDK. They are not blocked by Maya's runbook directly. If someone asks what is blocking Customer Portal, the first hop is Mobile. Only the follow-up question reaches Platform."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-34", "00:16:30", "person-sam", "QA matrix on iOS 18 and Android 15 is done. Store listing copy is locked. Feature work for home, wallet, and biometric unlock sits behind flags. None of that ships a login. The only blocker is migrated identity dual-write plus the signed SLA."),
    _seg("mtg-2026-09-03-mobile", "seg-mob-35", "00:17:10", "person-maya", "I will not ask you to move October 15. Platform will not ask you to slip. If we fail, it will be because the three overdues did not burn down, not because we quietly changed the date in a sidebar."),
]

STEERING_SEP2: list[dict[str, Any]] = [
    _seg("mtg-2026-09-02-steering", "seg-steer-01", "00:00:10", "person-dana", "Cross-project steering, September 2. This one is all-hands visibility, not the leadership-only session."),
    _seg("mtg-2026-09-02-steering", "seg-steer-02", "00:00:38", "person-jordan", "Graph recap for anyone new. Customer Portal depends on Mobile App Relaunch. Mobile depends on Platform Migration. That second edge is blocking."),
    _seg("mtg-2026-09-02-steering", "seg-steer-03", "00:01:10", "person-riley", "Portal's question is always: are we blocked? Directly, we are waiting on the mobile session SDK. We are not waiting on Maya's runbook ourselves."),
    _seg("mtg-2026-09-02-steering", "seg-steer-04", "00:01:42", "person-sam", "If you only ask what Portal depends on, the answer is Mobile. If you then ask whether Mobile is blocked, the answer is yes, by Platform."),
    _seg("mtg-2026-09-02-steering", "seg-steer-05", "00:02:10", "person-dana", "Say that in two hops out loud. We do not have a graph database. One lookup is not enough."),
    _seg("mtg-2026-09-02-steering", "seg-steer-06", "00:02:35", "person-maya", "Platform status: three overdues that explain the Mobile block. Runbook, dual-write lag, unsigned SLA."),
    _seg("mtg-2026-09-02-steering", "seg-steer-07", "00:03:05", "person-chris", "Pipeline is not on that chain. Compliance depends on us, separately. PII tags still open."),
    _seg("mtg-2026-09-02-steering", "seg-steer-08", "00:03:32", "person-jordan", "Correct. Do not mix the Portal story with the audit story."),
    _seg("mtg-2026-09-02-steering", "seg-steer-09", "00:03:50", "person-alex", "Marketing still has the July delay in a draft. I already reversed it. Please do not re-introduce November."),
    _seg("mtg-2026-09-02-steering", "seg-steer-10", "00:04:18", "person-dana", "We will not change October 15 in this meeting. Burn down the overdues."),
    _seg("mtg-2026-09-02-steering", "seg-steer-11", "00:04:40", "person-dana", "Decision: declare Mobile officially blocked on Platform until dual-write p95 is under two seconds and the identity SLA is signed."),
    _seg("mtg-2026-09-02-steering", "seg-steer-12", "00:05:15", "person-sam", "Thank you. That matches how we are running the RAID log."),
    _seg("mtg-2026-09-02-steering", "seg-steer-13", "00:05:35", "person-riley", "Risk for Portal: we are transitively blocked by Platform even though our direct dependency is Mobile. I will not tell my team we are 'fine' just because the first hop looks soft."),
    _seg("mtg-2026-09-02-steering", "seg-steer-14", "00:06:10", "person-riley", "Action: I will brief Portal that they are two hops behind Platform, not directly blocked. Due tomorrow."),
    _seg("mtg-2026-09-02-steering", "seg-steer-15", "00:06:38", "person-jordan", "I will keep the program RAID log to two explicit edges, not a hidden transitive flag."),
    _seg("mtg-2026-09-02-steering", "seg-steer-16", "00:07:00", "person-dana", "Decision: do not change October 15 dates in this steering; burn down platform overdues instead."),
    _seg("mtg-2026-09-02-steering", "seg-steer-17", "00:07:28", "person-maya", "Sam will join Platform weekly starting Friday."),
    _seg("mtg-2026-09-02-steering", "seg-steer-18", "00:07:45", "person-alex", "I will publish a team-readable note that Mobile is blocked on those Platform overdues."),
    _seg("mtg-2026-09-02-steering", "seg-steer-19", "00:08:10", "person-chris", "Compliance still on track if PII lands this month. Separate thread."),
    _seg("mtg-2026-09-02-steering", "seg-steer-20", "00:08:32", "person-dana", "We are not discussing hiring freeze or vendor fallbacks here. Different room, different visibility."),
    _seg("mtg-2026-09-02-steering", "seg-steer-21", "00:08:55", "person-jordan", "Noted. Team agendas should not include leadership-only items."),
    _seg("mtg-2026-09-02-steering", "seg-steer-22", "00:09:15", "person-dana", "Close. Two hops. Mobile blocked. Dates hold. Pipeline separate."),
    _seg("mtg-2026-09-02-steering", "seg-steer-23", "00:09:35", "person-jordan", "I will say the graph one more time because retrieval demos fail when we are sloppy. Customer Portal depends on Mobile App Relaunch. That edge is not currently marked blocking. Mobile App Relaunch depends on Platform Migration. That edge is blocking. A single lookup from Portal returns Mobile. It does not return Platform. You need a second call."),
    _seg("mtg-2026-09-02-steering", "seg-steer-24", "00:10:20", "person-riley", "Portal's RAID log will say we are waiting on the mobile session SDK. I will also brief the team that we are two hops behind Platform, not directly blocked. Those are different sentences. I do not want engineers assuming Maya's runbook is their blocker."),
    _seg("mtg-2026-09-02-steering", "seg-steer-25", "00:11:00", "person-sam", "Mobile is officially blocked until dual-write p95 is under two seconds and the identity SLA is signed. We reversed the November delay in August. October 15 holds. Flags stay dark. We will not ship a partial login on the monolith."),
    _seg("mtg-2026-09-02-steering", "seg-steer-26", "00:11:40", "person-maya", "Platform owns three overdues that explain that block: cutover runbook, dual-write lag, unsigned SLA. We are not changing October 15 in this steering. We burn those down. Hiring freeze and vendor fallbacks are not this meeting's visibility."),
    _seg("mtg-2026-09-02-steering", "seg-steer-27", "00:12:20", "person-chris", "Pipeline is a separate chain. Compliance depends on Data Pipeline Modernization for lineage evidence. PII classification is still open. Do not mix that story into Portal."),
    _seg("mtg-2026-09-02-steering", "seg-steer-28", "00:12:55", "person-dana", "Team agendas should not include leadership-only items from the August 19 room. If Minutes is asked to generate a Platform agenda for Maya, it should use team and all visibility, not leadership."),
    _seg("mtg-2026-09-02-steering", "seg-steer-29", "00:13:30", "person-alex", "I will publish a team-readable note that Mobile is blocked on those Platform overdues. I will not mention anything from the leadership steering."),
    _seg("mtg-2026-09-02-steering", "seg-steer-30", "00:14:00", "person-jordan", "Program RAID log keeps two explicit edges, not a hidden transitive flag. That is the honest single-hop versus graph point we will show in the next steering readout."),
    _seg("mtg-2026-09-02-steering", "seg-steer-31", "00:14:30", "person-dana", "I want Minutes to be able to answer two questions in sequence. First: what does Customer Portal depend on? Answer: Mobile App Relaunch. Second: and is that blocked? Answer: yes, by Platform Migration, blocking true, because of the overdue identity work. Narrate that the second question needed a second call."),
    _seg("mtg-2026-09-02-steering", "seg-steer-32", "00:15:20", "person-maya", "Please also say out loud that Compliance is not on that chain. Compliance depends on the pipeline. Mixing those graphs in an agenda is how we waste a steering hour."),
    _seg("mtg-2026-09-02-steering", "seg-steer-33", "00:15:55", "person-riley", "Portal human agenda for September 10 is session SDK and billing mocks. Billing mocks are done. Session SDK still waits on Mobile. I will not put Nimbus or the hiring freeze on that agenda. I do not have those facts in a team-visibility meeting."),
    _seg("mtg-2026-09-02-steering", "seg-steer-34", "00:16:35", "person-sam", "Mobile's upcoming weekly on September 10 should confirm October 15, list the three Platform overdues with owners, and keep flags dark. If Minutes cites the July delay as current, that is a bug. The current decision is keep the date. Please say that in the notes so retrieval has a checkable sentence."),
]

LEADERSHIP_AUG19: list[dict[str, Any]] = [
    _seg("mtg-2026-08-19-steering", "seg-lead-01", "00:00:09", "person-dana", "Leadership steering. Jordan only. This recording is leadership visibility. Do not paste into team Minutes."),
    _seg("mtg-2026-08-19-steering", "seg-lead-02", "00:00:40", "person-jordan", "Understood. Team weekly will get delivery facts, not this conversation."),
    _seg("mtg-2026-08-19-steering", "seg-lead-03", "00:01:02", "person-dana", "Finance closed Q3 early. We are instituting a hiring freeze through the 31st of October."),
    _seg("mtg-2026-08-19-steering", "seg-lead-04", "00:01:32", "person-jordan", "Platform asked for an identity SRE. Without that seat the on-call is Maya and Priya only."),
    _seg("mtg-2026-08-19-steering", "seg-lead-05", "00:02:00", "person-dana", "I will allow one exception: the identity SRE seat. Everything else waits."),
    _seg("mtg-2026-08-19-steering", "seg-lead-06", "00:02:28", "person-jordan", "I will not mention the freeze in the Platform weekly. Maya will hear 'cover on-call with current staff'."),
    _seg("mtg-2026-08-19-steering", "seg-lead-07", "00:02:55", "person-dana", "Decision: hiring freeze through 31 October except for the identity SRE seat."),
    _seg("mtg-2026-08-19-steering", "seg-lead-08", "00:03:22", "person-dana", "Risk: if the exception is slow, identity has no SRE until November and Mobile still launches in October."),
    _seg("mtg-2026-08-19-steering", "seg-lead-09", "00:03:50", "person-dana", "Action on me: open the exception req for that SRE seat during the freeze, due early September."),
    _seg("mtg-2026-08-19-steering", "seg-lead-10", "00:04:20", "person-jordan", "Second topic. In-house identity reversed Auth0 in August. If it slips past October 15 we have no vendor."),
    _seg("mtg-2026-08-19-steering", "seg-lead-11", "00:04:48", "person-dana", "Nimbus Auth reached out. Small team, their stack matches our dual-write design."),
    _seg("mtg-2026-08-19-steering", "seg-lead-12", "00:05:15", "person-dana", "Decision: explore acqui-hire of Nimbus Auth as a fallback if in-house identity slips past October 15."),
    _seg("mtg-2026-08-19-steering", "seg-lead-13", "00:05:48", "person-jordan", "That must not leak into team agendas. People will panic about jobs or about Auth0 coming back."),
    _seg("mtg-2026-08-19-steering", "seg-lead-14", "00:06:15", "person-dana", "Action: NDA pack for the Nimbus conversation, on me."),
    _seg("mtg-2026-08-19-steering", "seg-lead-15", "00:06:38", "person-jordan", "I will keep Minutes seeded for Maya without these two decisions."),
    _seg("mtg-2026-08-19-steering", "seg-lead-16", "00:07:00", "person-dana", "Park a contingency budget line for Nimbus. Leadership only."),
    _seg("mtg-2026-08-19-steering", "seg-lead-17", "00:07:25", "person-jordan", "October 15 public dates stay. We do not pre-announce a slip from this room."),
    _seg("mtg-2026-08-19-steering", "seg-lead-18", "00:07:50", "person-dana", "If a team user asks Minutes for 'all steering decisions', they should not see freeze or Nimbus."),
    _seg("mtg-2026-08-19-steering", "seg-lead-19", "00:08:20", "person-jordan", "I will test that path with a team-role profile before the next all-hands."),
    _seg("mtg-2026-08-19-steering", "seg-lead-20", "00:08:45", "person-dana", "Close. Freeze with one exception, Nimbus as quiet fallback, nothing for the team transcript."),
    _seg("mtg-2026-08-19-steering", "seg-lead-21", "00:09:10", "person-jordan", "I want to replay the freeze language so we do not drift. Through 31 October we hire nobody except the identity SRE. Maya will hear that on-call stays with current staff. She will not hear that Finance closed Q3 early or that we are buying optionality on a vendor."),
    _seg("mtg-2026-08-19-steering", "seg-lead-22", "00:09:55", "person-dana", "Correct. If Minutes is asked for steering decisions by a team-role user, freeze and Nimbus must not appear. The all-hands steering on September 2 can talk about the Portal-Mobile-Platform graph. This room cannot leak into that agenda."),
    _seg("mtg-2026-08-19-steering", "seg-lead-23", "00:10:35", "person-jordan", "Nimbus Auth is a twelve-person shop in Austin. Their dual-write story matches ours. An acqui-hire is cheaper than slipping October 15 in public. I will keep the NDA pack off shared drives. Action remains mine to assemble it."),
    _seg("mtg-2026-08-19-steering", "seg-lead-24", "00:11:15", "person-dana", "Budget line is a contingency, not a commitment. If in-house identity is green by October 1 we never spend it. If it is not, we move fast. That decision stays leadership visibility."),
    _seg("mtg-2026-08-19-steering", "seg-lead-25", "00:11:50", "person-jordan", "Risk restated: hiring freeze may leave identity without an SRE until November even with the exception in flight. I will not put that sentence in the Platform RAID log. I will put 'cover on-call with current staff'."),
    _seg("mtg-2026-08-19-steering", "seg-lead-26", "00:12:25", "person-dana", "If Legal asks why the exception exists, point them at Mobile's October 15 store date, not at Nimbus. Store dates are public. Vendor fallbacks are not."),
    _seg("mtg-2026-08-19-steering", "seg-lead-27", "00:12:55", "person-jordan", "I will test a team-role Minutes session that asks for all steering decisions. Expected: graph and Mobile blocked. Not expected: freeze, Nimbus, or the contingency budget."),
    _seg("mtg-2026-08-19-steering", "seg-lead-28", "00:13:30", "person-dana", "Good. Close again: freeze with one SRE exception, quiet Nimbus fallback, no leak into team Minutes, October 15 stays the public date."),
    _seg("mtg-2026-08-19-steering", "seg-lead-29", "00:14:00", "person-jordan", "I am leaving this recording in the leadership bucket. If someone files a ticket asking for 'the August steering transcript', access_role has to be leadership or they get nothing."),
    _seg("mtg-2026-08-19-steering", "seg-lead-30", "00:14:30", "person-dana", "That is the whole point of visibility. Team users can be excellent at their jobs without this context. We owe them delivery facts, not M&A chatter."),
    _seg("mtg-2026-08-19-steering", "seg-lead-31", "00:15:00", "person-jordan", "If we later generate a Platform agenda as Dana, it may include the freeze exception and the Nimbus fallback. If we generate the same agenda as Maya, those rows must not appear. That is the access-filtering demo, and it has to be real, not a prompt suggestion."),
    _seg("mtg-2026-08-19-steering", "seg-lead-32", "00:15:50", "person-dana", "Restate the two leadership decisions for the transcript. One: hiring freeze through 31 October except the identity SRE seat. Two: explore acqui-hire of Nimbus Auth if in-house identity slips past October 15. Both are active. Neither is for team Minutes."),
    _seg("mtg-2026-08-19-steering", "seg-lead-33", "00:16:30", "person-jordan", "The corresponding risks are also leadership visibility: freeze may leave identity without an SRE until November, and Nimbus is the only fallback if in-house slips. I will open the exception req and the NDA pack. Those actions stay on me."),
    _seg("mtg-2026-08-19-steering", "seg-lead-34", "00:17:10", "person-dana", "Last pass for the recording. This meeting is leadership visibility. Team Minutes must not retrieve it. The public story remains October 15, in-house identity, and covering on-call with current staff. Freeze mechanics and Nimbus live only here. If a team-role user asks for all steering decisions, they should get the September 2 graph, not this room. That filter is the demo and it has to actually work today."),
]

TRANSCRIPTS: list[dict[str, Any]] = PLATFORM_SEP4 + MOBILE_SEP3 + STEERING_SEP2 + LEADERSHIP_AUG19
